#!/bin/sh

rm -f deltadna-*.unitypackage

/Applications/Unity/Unity.app/Contents/MacOS/Unity \
    -batchMode \
    -quit \
    -nographics \
    -logFile ./unity-build.log \
    -executeMethod DeltaDNA.BuildScripts.ExportPackages
