#!/usr/bin/env bash

rm -f deltadna-*.unitypackage

# exporting in other than 5.6.5p1 creates backwards incompatible packages
UNITY=""
if [[ "$OSTYPE" == "darwin"* ]]; then
    if [ -d "/Applications/Unity_Build" ]; then
        UNITY=/Applications/Unity_Build/Unity.app/Contents/MacOS/Unity
    else
        echo "Failed to find '/Applications/Unity Build' directory"
        echo "Make sure it exists and points to a 5.6.x version of Unity"
        exit 1
    fi
elif [[ "$OSTYPE" == "msys" ]]; then
    echo "Exporting on Windows not supported due to incompatible line endings"
    exit 1
    #UNITY=/c/Program\ Files/Unity/Editor/Unity.exe
else
    exit 1
fi

"$UNITY" \
    -batchMode \
    -quit \
    -nographics \
    -projectPath $(pwd) \
    -logFile ./unity-build.log \
    -executeMethod DeltaDNA.BuildScripts.ExportPackage

if grep -q 'Exiting batchmode successfully now!' unity-build.log
then
    echo "Exported packages successfully."
else
    grep 'Fatal error!' unity-build.log
    grep -m 1 "executeMethod class 'BuildScripts' could not be found." unity-build.log
    echo "Failed to export packages."
fi
